/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'videoId' : VideoId,
}
export type CommentId = bigint;
export type ExternalBlob = Uint8Array;
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'avatarStorageKey' : [] | [ExternalBlob],
  'isPrivate' : boolean,
  'followerCount' : bigint,
  'followingCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VideoId = bigint;
export interface VideoPublic {
  'id' : VideoId,
  'isPublished' : boolean,
  'hashtags' : Array<string>,
  'createdAt' : Timestamp,
  'storageKey' : ExternalBlob,
  'caption' : string,
  'commentsCount' : bigint,
  'likesCount' : bigint,
  'viewsCount' : bigint,
  'uploaderId' : UserId,
}
export type WithdrawalId = bigint;
export interface WithdrawalRequestPublic {
  'id' : WithdrawalId,
  'status' : WithdrawalStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'rupeeAmount' : bigint,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'completed' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[VideoId, string], Comment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWithdrawalRequest' : ActorMethod<[bigint], WithdrawalRequestPublic>,
  'followUser' : ActorMethod<[UserId], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinBalance' : ActorMethod<[], bigint>,
  'getComments' : ActorMethod<[VideoId], Array<Comment>>,
  'getFeed' : ActorMethod<[bigint, bigint], Array<VideoPublic>>,
  'getFollowers' : ActorMethod<[UserId], Array<UserProfilePublic>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserProfilePublic>>,
  'getLikeCount' : ActorMethod<[VideoId], bigint>,
  'getMyReferralCode' : ActorMethod<[], string>,
  'getRupeeEquivalent' : ActorMethod<[bigint], bigint>,
  'getTrendingHashtags' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'getUserVideos' : ActorMethod<[UserId], Array<VideoPublic>>,
  'getVideo' : ActorMethod<[VideoId], [] | [VideoPublic]>,
  'getWithdrawalHistory' : ActorMethod<[], Array<WithdrawalRequestPublic>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[UserId], boolean>,
  'markWithdrawalCompleted' : ActorMethod<[WithdrawalId], boolean>,
  'recordAdWatch' : ActorMethod<[], bigint>,
  'recordDailyLogin' : ActorMethod<[], bigint>,
  'recordReferralReward' : ActorMethod<[string], boolean>,
  'recordVideoView' : ActorMethod<[VideoId], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'searchUsers' : ActorMethod<[string], Array<UserProfilePublic>>,
  'toggleLike' : ActorMethod<[VideoId], boolean>,
  'unfollowUser' : ActorMethod<[UserId], boolean>,
  'updateCallerAvatar' : ActorMethod<[ExternalBlob], undefined>,
  'uploadVideo' : ActorMethod<
    [ExternalBlob, string, Array<string>],
    VideoPublic
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];