/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VideoId = IDL.Nat;
export const CommentId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Comment = IDL.Record({
  'id' : CommentId,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'videoId' : VideoId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WithdrawalId = IDL.Nat;
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const WithdrawalRequestPublic = IDL.Record({
  'id' : WithdrawalId,
  'status' : WithdrawalStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'rupeeAmount' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfilePublic = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'avatarStorageKey' : IDL.Opt(ExternalBlob),
  'isPrivate' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
});
export const VideoPublic = IDL.Record({
  'id' : VideoId,
  'isPublished' : IDL.Bool,
  'hashtags' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'storageKey' : ExternalBlob,
  'caption' : IDL.Text,
  'commentsCount' : IDL.Nat,
  'likesCount' : IDL.Nat,
  'viewsCount' : IDL.Nat,
  'uploaderId' : UserId,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addComment' : IDL.Func([VideoId, IDL.Text], [Comment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWithdrawalRequest' : IDL.Func(
      [IDL.Nat],
      [WithdrawalRequestPublic],
      [],
    ),
  'followUser' : IDL.Func([UserId], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
  'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(VideoPublic)], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserProfilePublic)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserProfilePublic)], ['query']),
  'getLikeCount' : IDL.Func([VideoId], [IDL.Nat], ['query']),
  'getMyReferralCode' : IDL.Func([], [IDL.Text], []),
  'getRupeeEquivalent' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getTrendingHashtags' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getUserVideos' : IDL.Func([UserId], [IDL.Vec(VideoPublic)], ['query']),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(VideoPublic)], ['query']),
  'getWithdrawalHistory' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequestPublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'markWithdrawalCompleted' : IDL.Func([WithdrawalId], [IDL.Bool], []),
  'recordAdWatch' : IDL.Func([], [IDL.Nat], []),
  'recordDailyLogin' : IDL.Func([], [IDL.Nat], []),
  'recordReferralReward' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'recordVideoView' : IDL.Func([VideoId], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfilePublic)], ['query']),
  'toggleLike' : IDL.Func([VideoId], [IDL.Bool], []),
  'unfollowUser' : IDL.Func([UserId], [IDL.Bool], []),
  'updateCallerAvatar' : IDL.Func([ExternalBlob], [], []),
  'uploadVideo' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Vec(IDL.Text)],
      [VideoPublic],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VideoId = IDL.Nat;
  const CommentId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Comment = IDL.Record({
    'id' : CommentId,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'videoId' : VideoId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WithdrawalId = IDL.Nat;
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const WithdrawalRequestPublic = IDL.Record({
    'id' : WithdrawalId,
    'status' : WithdrawalStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'rupeeAmount' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfilePublic = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'avatarStorageKey' : IDL.Opt(ExternalBlob),
    'isPrivate' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
  });
  const VideoPublic = IDL.Record({
    'id' : VideoId,
    'isPublished' : IDL.Bool,
    'hashtags' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'storageKey' : ExternalBlob,
    'caption' : IDL.Text,
    'commentsCount' : IDL.Nat,
    'likesCount' : IDL.Nat,
    'viewsCount' : IDL.Nat,
    'uploaderId' : UserId,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addComment' : IDL.Func([VideoId, IDL.Text], [Comment], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWithdrawalRequest' : IDL.Func(
        [IDL.Nat],
        [WithdrawalRequestPublic],
        [],
      ),
    'followUser' : IDL.Func([UserId], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
    'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(VideoPublic)], ['query']),
    'getFollowers' : IDL.Func(
        [UserId],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [UserId],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'getLikeCount' : IDL.Func([VideoId], [IDL.Nat], ['query']),
    'getMyReferralCode' : IDL.Func([], [IDL.Text], []),
    'getRupeeEquivalent' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getTrendingHashtags' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getUserVideos' : IDL.Func([UserId], [IDL.Vec(VideoPublic)], ['query']),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(VideoPublic)], ['query']),
    'getWithdrawalHistory' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequestPublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'markWithdrawalCompleted' : IDL.Func([WithdrawalId], [IDL.Bool], []),
    'recordAdWatch' : IDL.Func([], [IDL.Nat], []),
    'recordDailyLogin' : IDL.Func([], [IDL.Nat], []),
    'recordReferralReward' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'recordVideoView' : IDL.Func([VideoId], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'toggleLike' : IDL.Func([VideoId], [IDL.Bool], []),
    'unfollowUser' : IDL.Func([UserId], [IDL.Bool], []),
    'updateCallerAvatar' : IDL.Func([ExternalBlob], [], []),
    'uploadVideo' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Vec(IDL.Text)],
        [VideoPublic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };